theme = "custom_catppuccin_mocha"
# theme = "catppuccin_mocha"

[editor]
# auto-format = true
line-number = "relative"
mouse = true
bufferline = "multiple"
color-modes = true
true-color = true #fix colours over ssh

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
esc = ["collapse_selection", "keep_primary_selection"]
# lazy git integration
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw", ":reload-all"]
# yazi integration
C-e = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
X = ["extend_line_up", "extend_to_line_bounds"]
C-u = ["half_page_up", "align_view_center"]
C-d = ["half_page_down", "align_view_center"]
D = "kill_to_line_end" 
"C-A-c" = [
  ":echo %sh{echo '%{buffer_name}' | pbcopy}",
  ":echo Copied %{buffer_name}"
]
"C-A-y" = [
  ":echo %sh{echo 'File: %{buffer_name}, Line Start: %{selection_line_start}, Line End: %{selection_line_end} \n\n %{selection}' | pbcopy}",
  ":echo Copied %{buffer_name} %{selection_line_start} %{selection_line_end} \n\n %{selection}"
]

[keys.select]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
"C-A-c" = [
  ":echo %sh{echo '%{buffer_name}' | pbcopy}",
  ":echo Copied %{buffer_name}"
]
"C-A-y" = [
  ":echo %sh{echo 'File: %{buffer_name}, Line Start: %{selection_line_start}, Line End: %{selection_line_end} \n\n %{selection}' | pbcopy}",
  ":echo Copied %{buffer_name} %{selection_line_start} %{selection_line_end} \n\n %{selection}"
]

[keys.normal."space"]
"<" = "file_picker_in_current_buffer_directory"

[editor.file-picker]
hidden = false # show hidden files as in starting with a dot
git-global = false # show files hidden by git globally


# [editor.inline-diagnostics]
# "cursor-line" = "warning"
# "other-lines" = "error"
